application: ducopro-idfix
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /favicon\.ico
  static_files: idfix.png
  upload: idfix\.png

- url: /test\.php
  script: test.php

- url: /cron/.*
  script: cron.php
  login: admin
  
- url: .*/.*/.*/.*/.*/pushtask
  script: index.php
  login: admin

- url: .*/.*/.*/.*/.*/uploadforgoogle
  script: index.php
  login: admin
  
- url: /.*/.*
  script: index.php

- url: .*
  static_files: redirect.html
  upload: redirect\.html